### PR TITLE
Merge Bad Changes into master before presentation. 

### PR DESCRIPTION
**Pull request by helloimowen**
Feel free to keep committing, but I want to merge this in before the presentation tomorrow.

### CODE REVIEW

**Comment by helloimowen** [comment]
I love that you get a dollar for each paper graded . It's a lot more fun. 
It should probably be an upgrade. Will add it when that system is in.

**Comment by OverloadedWolf** [comment]
Should we merge MoneyStuff in as well?

**Comment by helloimowen** [comment]
Yup, I can merge it in to bad_changes again.

**Comment by helloimowen** [comment]
I don't know if anyone's planning on making any changes tonight (upgrades need to be finished and Alec has not pushed) but I'm going to merge to master now.

**Pull request merged**
